name: Oscar Bjorkman's Blog
description: Blogging about stuffs
meta_description: "Oscar Bjorkman Blogging about stuffs"

aboutPage: true

markdown: redcarpet
highlighter: pygments

baseurl: /
domain_name: 'http://stereopoly.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://stereopoly.github.io'
author:         'Oscar Bjorkman'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
