# Site settings
title: Oscar Bjorkman
description: >
  Oscar Bjorkman's School Posts

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stereopoly.github.io" # the base hostname & protocol for your site

author:
  fullname: Oscar Bjorkman
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: Stereopoly
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
