# Site settings
title: Oscar Bjorkman's Blog
email: oscarrbjorkman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Oscar Bjorkman's blog about water-cooler talk, banter, and whatever else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stereopoly.github.io" # the base hostname & protocol for your site
github_username:  Stereopoly

# Build settings
markdown: kramdown
